package messages

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *PlaceOrder) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "CommonHeader":
			err = z.CommonHeader.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "CommonHeader")
				return
			}
		case "c":
			z.ClOrderId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ClOrderId")
				return
			}
		case "u":
			z.UserId, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "UserId")
				return
			}
		case "s":
			z.SymbolId, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SymbolId")
				return
			}
		case "S":
			z.Side, err = dc.ReadInt8()
			if err != nil {
				err = msgp.WrapError(err, "Side")
				return
			}
		case "t":
			z.Type, err = dc.ReadInt8()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "T":
			z.TimeInForce, err = dc.ReadInt8()
			if err != nil {
				err = msgp.WrapError(err, "TimeInForce")
				return
			}
		case "q":
			z.Quantity, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Quantity")
				return
			}
		case "Q":
			z.QuoteOrderQty, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "QuoteOrderQty")
				return
			}
		case "p":
			z.Price, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Price")
				return
			}
		case "P":
			z.StopPrice, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "StopPrice")
				return
			}
		case "V":
			z.SelfTradePreventionMode, err = dc.ReadInt8()
			if err != nil {
				err = msgp.WrapError(err, "SelfTradePreventionMode")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PlaceOrder) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 12
	// write "CommonHeader"
	err = en.Append(0x8c, 0xac, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72)
	if err != nil {
		return
	}
	err = z.CommonHeader.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "CommonHeader")
		return
	}
	// write "c"
	err = en.Append(0xa1, 0x63)
	if err != nil {
		return
	}
	err = en.WriteString(z.ClOrderId)
	if err != nil {
		err = msgp.WrapError(err, "ClOrderId")
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.UserId)
	if err != nil {
		err = msgp.WrapError(err, "UserId")
		return
	}
	// write "s"
	err = en.Append(0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SymbolId)
	if err != nil {
		err = msgp.WrapError(err, "SymbolId")
		return
	}
	// write "S"
	err = en.Append(0xa1, 0x53)
	if err != nil {
		return
	}
	err = en.WriteInt8(z.Side)
	if err != nil {
		err = msgp.WrapError(err, "Side")
		return
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt8(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "T"
	err = en.Append(0xa1, 0x54)
	if err != nil {
		return
	}
	err = en.WriteInt8(z.TimeInForce)
	if err != nil {
		err = msgp.WrapError(err, "TimeInForce")
		return
	}
	// write "q"
	err = en.Append(0xa1, 0x71)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Quantity)
	if err != nil {
		err = msgp.WrapError(err, "Quantity")
		return
	}
	// write "Q"
	err = en.Append(0xa1, 0x51)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.QuoteOrderQty)
	if err != nil {
		err = msgp.WrapError(err, "QuoteOrderQty")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Price)
	if err != nil {
		err = msgp.WrapError(err, "Price")
		return
	}
	// write "P"
	err = en.Append(0xa1, 0x50)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.StopPrice)
	if err != nil {
		err = msgp.WrapError(err, "StopPrice")
		return
	}
	// write "V"
	err = en.Append(0xa1, 0x56)
	if err != nil {
		return
	}
	err = en.WriteInt8(z.SelfTradePreventionMode)
	if err != nil {
		err = msgp.WrapError(err, "SelfTradePreventionMode")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PlaceOrder) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 12
	// string "CommonHeader"
	o = append(o, 0x8c, 0xac, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72)
	o, err = z.CommonHeader.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "CommonHeader")
		return
	}
	// string "c"
	o = append(o, 0xa1, 0x63)
	o = msgp.AppendString(o, z.ClOrderId)
	// string "u"
	o = append(o, 0xa1, 0x75)
	o = msgp.AppendInt32(o, z.UserId)
	// string "s"
	o = append(o, 0xa1, 0x73)
	o = msgp.AppendInt32(o, z.SymbolId)
	// string "S"
	o = append(o, 0xa1, 0x53)
	o = msgp.AppendInt8(o, z.Side)
	// string "t"
	o = append(o, 0xa1, 0x74)
	o = msgp.AppendInt8(o, z.Type)
	// string "T"
	o = append(o, 0xa1, 0x54)
	o = msgp.AppendInt8(o, z.TimeInForce)
	// string "q"
	o = append(o, 0xa1, 0x71)
	o = msgp.AppendInt64(o, z.Quantity)
	// string "Q"
	o = append(o, 0xa1, 0x51)
	o = msgp.AppendInt64(o, z.QuoteOrderQty)
	// string "p"
	o = append(o, 0xa1, 0x70)
	o = msgp.AppendInt64(o, z.Price)
	// string "P"
	o = append(o, 0xa1, 0x50)
	o = msgp.AppendInt64(o, z.StopPrice)
	// string "V"
	o = append(o, 0xa1, 0x56)
	o = msgp.AppendInt8(o, z.SelfTradePreventionMode)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PlaceOrder) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "CommonHeader":
			bts, err = z.CommonHeader.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "CommonHeader")
				return
			}
		case "c":
			z.ClOrderId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ClOrderId")
				return
			}
		case "u":
			z.UserId, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserId")
				return
			}
		case "s":
			z.SymbolId, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SymbolId")
				return
			}
		case "S":
			z.Side, bts, err = msgp.ReadInt8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Side")
				return
			}
		case "t":
			z.Type, bts, err = msgp.ReadInt8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "T":
			z.TimeInForce, bts, err = msgp.ReadInt8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TimeInForce")
				return
			}
		case "q":
			z.Quantity, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Quantity")
				return
			}
		case "Q":
			z.QuoteOrderQty, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "QuoteOrderQty")
				return
			}
		case "p":
			z.Price, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Price")
				return
			}
		case "P":
			z.StopPrice, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StopPrice")
				return
			}
		case "V":
			z.SelfTradePreventionMode, bts, err = msgp.ReadInt8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SelfTradePreventionMode")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PlaceOrder) Msgsize() (s int) {
	s = 1 + 13 + z.CommonHeader.Msgsize() + 2 + msgp.StringPrefixSize + len(z.ClOrderId) + 2 + msgp.Int32Size + 2 + msgp.Int32Size + 2 + msgp.Int8Size + 2 + msgp.Int8Size + 2 + msgp.Int8Size + 2 + msgp.Int64Size + 2 + msgp.Int64Size + 2 + msgp.Int64Size + 2 + msgp.Int64Size + 2 + msgp.Int8Size
	return
}
